name: ci

on:
  push:

jobs:
  build-to-ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build bundle
        run: |
          sudo apt-get update
          # Install Java and dependencies (NOT clojure from apt)
          sudo apt-get install -y curl unzip git openjdk-11-jdk rlwrap

          # Install official Clojure CLI tools
          curl -L -O https://github.com/clojure/brew-install/releases/latest/download/linux-install.sh
          chmod +x linux-install.sh
          sudo ./linux-install.sh

          # Verify installation
          clj --version

          # Now build with proper Clojure CLI (supports -X flag)
          mkdir -p target/bundle/doc
          make target/bundle/config target/bundle/bin target/bundle/lrsql.jar target/bundle/admin target/bundle/LICENSE target/bundle/NOTICE target/bundle/customization target/bundle/bench.jar target/bundle/bench

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.actor }}/lrsql:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max